//make the global.css file apply to the whole site
import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
 
export const metadata: Metadata = {
  title: 'Website: Yael Borger',
  description: 'Website generated by create next app, designed and used by Yael Borger',
}


//upon first creating:
export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    )
  }