export const casesData = [
    {
        title: "Ablockalypse",
        image: "/ablockalypse.png",
        summary: "A pixel platformer with tetris-style platform building",
        slug: "portfolio/cases/ablockalypse",
        tags: ["Software", "Design", "Lua", "Tic80"],
    },
    {
        title: "EXAMPLE Title",
        image: "/art sign.png",
        summary: "This is a brief summary of case study 1.",
        slug: "portfolio/cases/example",
        tags: ["EX"],
    },
    {
        title: "MyStudyBuddy",
        image: "/mystudybuddy.jpg",
        summary: "A Google Chrome extension for reminders that are often forgotten by busy college students",
        slug: "portfolio/cases/mystudybuddy",
        tags: ["Software", "UI / UX", "JavaScript", "HTML", "CSS"],
    },
    {
        title: "Our Kids Read: Website Redesign",
        image: "/okr_imgs/preferred.png",
        summary: "Leading a full redesign of the Our Kids Read website",
        slug: "portfolio/cases/ourkidsread",
        tags: ["UI / UX", "Design"],
    },
    {
        title: "SwatNinja",
        image: "/art sign.png",
        summary: "An augmented reality (AR) game based on 'Fruit Ninja' including hand-recognition technology and custom sprites",
        slug: "portfolio/cases/swatninja",
        tags: ["Software", "Design", "JavaScript"],
    },
    {
        title: "Snap.Nutrition",
        image: "/art sign.png",
        summary: "An AI-coded application for recognizing food from images and reporting back nutrition information",
        slug: "portfolio/cases/snapnutrition",
        tags: ["Product Builder", "AI", "UI / UX"],
    },
    {
        title: "Find My Restroom",
        image: "/art sign.png",
        summary: "An AI-coded demo application for finding publicly available restrooms based on accessibility and distance",
        slug: "portfolio/cases/findmyrestroom",
        tags: ["Product Builder", "AI"],
    },
]